In [8]:
import pandas as pd
df = pd.read_csv("data1.csv")
df
programing_year = {
    'name' = ['c','python','php']
    'year' = ['2017','2018','2019']
    'czz' = ['learning','robotice','web development']
}

        day  tem  windspeed  event
0  1/1/2022   32          6   rain
1  1/2/2022   45          7  sunny
2  1/3/2022   25          2   snow
3  1/4/2022   30          7   snow
4  1/5/2022   32          6  sunny
5  1/6/2022   45          5  sunny
6  1/7/2022   28          2   snow
7  1/8/2022   15          3   rain
8  1/9/2022   32          7   rain

####